site:
  title: Documentation Incongrue
  url: https://constructions-incongrues.github.io/musiqueapproximative
  start_page: ROOT::index.adoc

content:
  sources:
    - url: .
      branches: [main, v1.0.*]
      worktrees: false
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./build/site

asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    kroki-fetch-diagram: true
    kroki-server-url: https://kroki.io
