# yaml-language-server: $schema=../schemas/regles.schema.json

# Règlement intérieur de l'EHPAD
regles:
  - probability: 0.5
    query: query.title ~ /.*(phone|t[eé]l[eé]phone|allo).*/i
    recettes: [mamie_allo]