# yaml-language-server: $schema=../schemas/regles.schema.json

# Régulation typographique de l'appétit
regles:
  - probability: 0.3
    query: query.title ~ /(.*)/i
    recettes: [consonnard, voyelliste]
