# yaml-language-server: $schema=../schemas/regles.schema.json

# RÃ¨gles en vrac
regles:
  - probability: 0.7
    query: query.title ~ /.*(amour|love).*/i
    recettes: [amour]
  - probability: 0.7
    query: query.title ~ /.*robot.*/i
    recettes: [robot]
  - probability: 0.7
    query: query.title ~ /.*(fish|poisson).*/i
    recettes: [fish]
  - probability: 0.7
    query: query.title ~ /.*(morte?s?|deaths?|dead).*/i
    recettes: [postillons_mort]
  - probability: 0.7
    query: query.title ~ /.*(musique|music).*/i
    recettes: [musique]
  - probability: 0.7
    query: query.title ~ /.*bleu.*/i || query.artist ~ /.*bleu.*/i
    recettes: [bleu]
  - probability: 0.7
    query: query.title ~ /.*(noir|black).*/i
    recettes: [noir]
  - probability: 0.7
    query: query.title ~ /.*(light|lumiere).*/i
    recettes: [light]
  - probability: 1
    query: query.title ~ /.*(danse).*/i
    recettes: [danse]
