# yaml-language-server: $schema=../schemas/regles.schema.json

# Regles pour les desastres de manipulation de texte
regles:
  # DÃ©sastres "mangelettres"
  - query: "query.title ~ /(.*)/i"
    recettes: [consonnard, voyelliste]
    probability: 0.05
