---
name: Lint

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

permissions: {}

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # Super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false

      - name: Installer Asciidoctor
        run: sudo apt-get install -y asciidoctor

      - name: Valider les fichiers AsciiDoc
        run: |
          find . -name "*.adoc" -not -path "*/vendor/*" -not -path "*/node_modules/*" -not -path "./build/*" -not -path "./var/*" -exec asciidoctor --failure-level WARNING -o /dev/null {} +

      - name: Super-Linter
        uses: super-linter/super-linter@v8.3.2
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # Validate only changed files on push/PR
          VALIDATE_ALL_CODEBASE: false
          
          # Default branch
          DEFAULT_BRANCH: main

          VALIDATE_JSON: true
          VALIDATE_YAML: true
          VALIDATE_TOML: true
          VALIDATE_PHP: true
          VALIDATE_JSCPD: true
          VALIDATE_NATURAL_LANGUAGE: true
          PRE_COMMIT: true
          
          # Filter regex for files to exclude
          FILTER_REGEX_EXCLUDE: .*/(vendor|node_modules|build|var|web/swf)/.*
  

